String.toLocaleString({

	"it": {
    "%game-intro"           : "Join the <strong>Mr.Incredibles!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"https://0x0800.github.io/2048-CUPCAKES/\">2048 Cupcakes</a> </a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'Dead',
    '%4'                    : 'Extra Cringe',
    '%8'                    : 'Cringe',
    '%16'                   : 'Normal',
    '%32'                   : 'Happy',
    '%64'                   : 'Extra Happy',
    '%128'                  : 'Cool',
    '%256'                  : 'Extra Cool',
    '%512'                  : 'Mega Cool',
    '%1024'                 : 'Mad',
    '%2048'                 : 'Insane',
    '%4096'                 : 'God',
    '%8192'                 : 'Universe',
    '%p0'                   : 'Dead',
    '%p4'                   : 'Extra Cringe',
    '%p8'                   : 'Cringe',
    '%p16'                  : 'Normal',
    '%p32'                  : 'Happy',
    '%p64'                  : 'Extra Happy',
    '%p128'                 : 'Cool',
    '%p256'                 : 'Extra Cool',
    '%p512'                 : 'Mega Cool',
    '%p1024'                : 'Mad',
    '%p2048'                : 'Insane',
    '%p4096'                : 'God',
    '%p8192'                : 'Universe'

	},

  "en": {
    "%game-intro"           : "Join the <strong>Mr.Incredibles!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"https://0x0800.github.io/2048-CUPCAKES/\">2048 Cupcakes</a> </a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'Dead',
    '%4'                    : 'Extra Cringe',
    '%8'                    : 'Cringe',
    '%16'                   : 'Normal',
    '%32'                   : 'Happy',
    '%64'                   : 'Extra Happy',
    '%128'                  : 'Cool',
    '%256'                  : 'Extra Cool',
    '%512'                  : 'Mega Cool',
    '%1024'                 : 'Mad',
    '%2048'                 : 'Insane',
    '%4096'                 : 'God',
    '%8192'                 : 'Universe',
    '%p0'                   : 'Dead',
    '%p4'                   : 'Extra Cringe',
    '%p8'                   : 'Cringe',
    '%p16'                  : 'Normal',
    '%p32'                  : 'Happy',
    '%p64'                  : 'Extra Happy',
    '%p128'                 : 'Cool',
    '%p256'                 : 'Extra Cool',
    '%p512'                 : 'Mega Cool',
    '%p1024'                : 'Mad',
    '%p2048'                : 'Insane',
    '%p4096'                : 'God',
    '%p8192'                : 'Universe'
  }

});
